// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClvKzhCRd3gHoyEUcKl_SZuQsxD0t41pg',
    appId: '1:537302840171:web:7fcf8cc2243888fcbf122e',
    messagingSenderId: '537302840171',
    projectId: 'tiktok-clone-with-nico',
    authDomain: 'tiktok-clone-with-nico.firebaseapp.com',
    storageBucket: 'tiktok-clone-with-nico.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Zy4HZkJYbv3CGtxqxhGmODV7mRyjd6g',
    appId: '1:537302840171:android:2e820bdb92922296bf122e',
    messagingSenderId: '537302840171',
    projectId: 'tiktok-clone-with-nico',
    storageBucket: 'tiktok-clone-with-nico.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyQcrTKAa43sLC5eeVyQzQ5zWTyOk0J-c',
    appId: '1:537302840171:ios:3338370d22b99ee9bf122e',
    messagingSenderId: '537302840171',
    projectId: 'tiktok-clone-with-nico',
    storageBucket: 'tiktok-clone-with-nico.appspot.com',
    androidClientId: '537302840171-u4j4fr5acvg93isaor3rkt5re8841jno.apps.googleusercontent.com',
    iosClientId: '537302840171-ico3emamto3ql1u5pec1kknalbhrofno.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyQcrTKAa43sLC5eeVyQzQ5zWTyOk0J-c',
    appId: '1:537302840171:ios:3338370d22b99ee9bf122e',
    messagingSenderId: '537302840171',
    projectId: 'tiktok-clone-with-nico',
    storageBucket: 'tiktok-clone-with-nico.appspot.com',
    androidClientId: '537302840171-u4j4fr5acvg93isaor3rkt5re8841jno.apps.googleusercontent.com',
    iosClientId: '537302840171-ico3emamto3ql1u5pec1kknalbhrofno.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
